### ISSUE TITLE
Losses are abnormal

### ISSUE THREAD

**Issue by poodarchu** [idstcv/DR_loss#2]
after training the model as stated in readme, the classification loss is only about 0.009, and regression loss is about 1.0 at the beginning.

**Comment by qian-qi** [comment]
Please check your environment. The classification loss should be about 2 after initialization. It is directly from 4xlog(1+exp(6x0.5))/6=2.03.
After training, the classification loss should be similar to the regression loss.

**Comment by poodarchu** [comment]
![image](https://user-images.githubusercontent.com/11813362/79295895-7ce5ee00-7f0c-11ea-8233-aa05d05115dd.png)

**Comment by poodarchu** [comment]
![image](https://user-images.githubusercontent.com/11813362/79295930-95560880-7f0c-11ea-977b-c3be98f5075d.png)

I think it doesn't have relationship with the environment. and the modification is simple. So I think maybe you miss some details?

**Comment by qian-qi** [comment]
I find a potential problem in your code. The normalization term is from focal loss and we don't have it for the dr loss.
![Screen Shot 2020-04-14 at 20 35 36](https://user-images.githubusercontent.com/55555287/79296272-cd6b3600-7e8f-11ea-98f0-c378b23fb5f6.png)

**Comment by poodarchu** [comment]
ok thanks.
