### ISSUE TITLE
Is this possible to using DR loss for multi-label problem?

### ISSUE THREAD

**Issue by SHENG-KAI-HUANG** [idstcv/DR_loss#4]
As title, I am handling the problem is multi-label but I am not sure how to modify the code to do this.
So can anyone give me a hint?

**Comment by qian-qi** [comment]
The multi-label problem can be decomposed into a series of binary classification problem, where each subproblem is for a single label. Maybe you can apply the loss with this setting.

**Comment by SHENG-KAI-HUANG** [comment]
> The multi-label problem can be decomposed into a series of binary classification problem, where each subproblem is for a single label. Maybe you can apply the loss with this setting.

Thank you! I will try it when I have time!
