### ISSUE TITLE
关于PRIOR_PROB的问题

### ISSUE THREAD

**Issue by liliangqi** [idstcv/DR_loss#5]
你好，我对MaskRCNNBenchmark不是很熟悉，不太了解配置文件中PRIOR_PROB的含义，能否麻烦您说明一下？

**Comment by qian-qi** [comment]
这是模型初始化时候的分类概率，focal loss的paper中是这么描述的
<img width="333" alt="Screen Shot 2020-06-15 at 01 12 36" src="https://user-images.githubusercontent.com/55555287/84633621-860c2080-aea5-11ea-9412-06708b6dc502.png">

**Comment by liliangqi** [comment]
哦哦，是这个啊。了解了，感谢！
