### ISSUE TITLE
Performance of GIoU

### ISSUE THREAD

**Issue by Joker316701882** [idstcv/DR_loss#6]
Hi. @qian-qi 

Have you tried to replace SmoothL1 with GIoU Loss? In this work, the regression part is irrelevant to the classification/distributional ranking part, so I assume that GIoU could improve the final performance of DRLoss. However, in my own implementation, the GIoU Loss brings performance drop about 0.2mAP, which is a little bit confusing. Have you tried that?

Bests.

**Comment by qian-qi** [comment]
I didn't try GIoU loss before. Maybe you can check the scales of the classification loss and regression loss. If they are significantly different, you can tune the weight of the loss to make those losses have the similar scale, which is important for the performance.

**Comment by Joker316701882** [comment]
Thank you for your reply. I'll try that.
